[workspace]
members = [
    "ded",
    "examples/counter",
    "examples/todomvc",
]

[replace]
# "ded:0.1.0" = {path = "ded"}

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
